import { IMovie } from '../../models/Movie'

export const testMoviesData = [{'Title':'The Lord of the Rings: The Fellowship of the Ring','Year':'2001','imdbID':'tt0120737','Type':'movie','Poster':'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Return of the King','Year':'2003','imdbID':'tt0167260','Type':'movie','Poster':'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Two Towers','Year':'2002','imdbID':'tt0167261','Type':'movie','Poster':'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Rings of Power','Year':'2022–','imdbID':'tt7631058','Type':'series','Poster':'https://m.media-amazon.com/images/M/MV5BNmVmZGQ2ZTctYzE4NC00YzkxLThhNjYtNGIyZjJmZGEwMjUzXkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings','Year':'1978','imdbID':'tt0077869','Type':'movie','Poster':'https://m.media-amazon.com/images/M/MV5BZmI4ZmIxOGQtMGY2ZS00Y2Y5LTllMDItYzllOWFmMTNlMmY2XkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The War of the Rohirrim','Year':'2024','imdbID':'tt14824600','Type':'movie','Poster':'https://m.media-amazon.com/images/M/MV5BOTg4OTgyMDYtMDA0NC00ZjJhLWJiOGMtMjlkM2ZjNTgxNGI0XkEyXkFqcGc@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Two Towers','Year':'2002','imdbID':'tt0347436','Type':'game','Poster':'https://m.media-amazon.com/images/M/MV5BODI0Mzk3OTM4N15BMl5BanBnXkFtZTgwMTM4MTk4MDE@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Return of the King','Year':'2003','imdbID':'tt0387360','Type':'game','Poster':'https://m.media-amazon.com/images/M/MV5BMjE5NTQwMTY5MV5BMl5BanBnXkFtZTgwODcwNjUwMTE@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Battle for Middle-Earth','Year':'2004','imdbID':'tt0412935','Type':'game','Poster':'https://m.media-amazon.com/images/M/MV5BYWI5ODU0ZGEtYTA4YS00YzliLWJiZjEtYThkNTBkNTY1Y2FhXkEyXkFqcGdeQXVyNDAzNzA0MzE@._V1_SX300.jpg'},{'Title':'The Lord of the Rings: The Battle for Middle-Earth II','Year':'2006','imdbID':'tt0760172','Type':'game','Poster':'https://m.media-amazon.com/images/M/MV5BZTFlNTg5NzgtZmUyNS00MWJjLWFmNDktZmNiODEzZWY2YjgwXkEyXkFqcGdeQXVyNDAzNzA0MzE@._V1_SX300.jpg'}]

export const getData = async (searchText: string): Promise<IMovie[]> => {
    switch (true) {
        case searchText.includes('lotr'):
            return testMoviesData
        case searchText === '':
            return []
        default:
            throw Error('API call failed')
    }
}